services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: 'false'
    volumes:
      - ./keycloak/realm-config:/opt/keycloak/data/import
    command: start-dev --import-realm
    ports:
      - "8888:8080"
